spring:
  application:
    name: portfolio-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/db_portfolio}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  flyway:
    enabled: false

server:
  port: 9004

internal:
  api-key: ${INTERNAL_API_KEY}
