spring:
  application:
    name: portfolio-service
  datasource:
    url: jdbc:postgresql://localhost:5433/db_portfolio
    username: postgres
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true

server:
  port: 8083

internal:
  api-key: secret123